def draw_mytree():
    print("               *")
    print("              * *             ")
    print("             * * *            ")
    print("            * * * *           ")
    print("           * * * * *          ")
    print("          * * * * * *         ")
    print("         * * * * * * *        ")
    print("        * * * * * * * *       ")
    print("       * * * * * * * * *      ")
    print("      * * * * * * * * * *     ")
    print("     * * * * * * * * * * *    ")
    print("    * * * * * * * * * * * *   ")
    print("              * *             ")
    print("              * *             ")
    print("              * *             ")
    print("              * *             ")
    print("              ***             ")


draw_mytree()
